### ISSUE TITLE
Idea: Move docs to the root of repo

### ISSUE THREAD

**Issue by denysdovhan** [wix-incubator/autoviews#65]
I guess `/packages/docs` folder must be moved to the `/website` folder.

Ideally, `packages` folder should contain only packages that get published on `npm`. `docs` is not being published that way.

Having `docs` within `packages` also introduces additional challenges with running build scripts. For example, before publishing, we have to build every package, excluding `docs` folder.

**Comment by tyv** [comment]
yes! totally support it. we need to merge @yoavaa PR when it is ready and then move.

**Comment by tyv** [comment]
I guess we can go with gh-pages branch and automation according to https://docusaurus.io/docs/deployment#deploying-to-github-pages

**Comment by tyv** [comment]
https://wix-incubator.github.io/autoviews/

**Comment by denysdovhan** [comment]
@tyv this doesn't seem to be resolved. `website` is still inside the `packages` folder. I was talking about moving it from `packages` to the root of the repo, so the website would not go through lerna pipelines.
